project:
  type: book
  output-dir: docs

book:
  page-navigation: true
  title: "Practical and Innovative Analytics in Data Science"
  author: "phonchi"
  date: "02/13/2023"
  chapters:
        - index.qmd
        - 01_end_to_end_machine_learning_project.ipynb
        - 02_Dataset.ipynb
        - 03_Relational_Database_and_data_wrangling.ipynb
        - 04_Clean_feature_engineering.ipynb
        - 05_Feature_selection_extraction.ipynb
        - 06_XAI.ipynb
        - 07_Deploy.ipynb
        - 08_neural_nets_with_tensorflow.ipynb
        - 09_Convolutional_NeuralNetworks_tensorflow.ipynb
        - 10_Recurrent_Neural_Networks.ipynb
        - 11_Transfer_learning.ipynb
        - 12_Representation_learning.ipynb
        - 13_Hyperparameter.ipynb
  appendices:
        - NumPy_tutorial.ipynb
        - Colab_tutorial.ipynb
        - kaggle-explore.ipynb
        - 08_neural_nets_with_pytorch.ipynb
        - 09_Convolutional_NeuralNetworks_pytorch.ipynb
  search:
    location: sidebar
format:
  html:
    theme: cosmo
    cover-image: cover.jpg